#############################################################
#
# Ref to the ARTICLE 
# 
# Code to compute calculations presented in: https://www.biorxiv.org/content/10.1101/2021.12.20.472907v3
#
# Figure 7a
#  
# max.coulter@xelect.co.uk
# d.bulgarelli@dundee.ac.uk 
#
#############################################################

#############################################################
# Clean-up the memory and start a new session
#############################################################

rm(list=ls())
dev.off()

#############################################################
# Libraries required
#############################################################

#load required packages
library(ggplot2)

#retrieve R and package versions and compare to the uploaded file in GitHub for the reproducibility of the code
sessionInfo()

setwd("/cluster/db/R_shared/3H_manuscript/")

#Import count data (CPM genes): this input is generated by the script used for Figure 4 and provided as souce file
load("/cluster/db/R_shared/3H_manuscript/RNAquant_analysis_data/genes_dge.RData")
gene_counts <- as.data.frame(genes_dge$counts)
colnames(gene_counts)
#Identify the candidate
gene_name <- "BaRT2v18chr3HG123500"
#subset for the the candidate within the count genes
NLR_plot <- gene_counts[gene_name,]
NLR_plot

#create the mapping file
genotype <- c("124_17", "124_17", "124_17", "124_17", "124_17", "124_52", "124_52", "124_52", "124_52", "124_52", "Barke", "Barke", "Barke", "Barke", "Barke")
genotype <-as.data.frame(genotype)
rownames(genotype) <- colnames(gene_counts)
genotype 

#combine these datasets with the design file
design_counts <- cbind(genotype, t(gene_counts))
rownames(design_counts)

#Define a dataframe with only the NLR candidate
gene_name <- "BaRT2v18chr3HG123500"
counts_NLR <- as.data.frame(design_counts[, gene_name])
rownames(counts_NLR) <- rownames(design_counts)
colnames(counts_NLR) <- c("CPM")

design_NLR <- cbind(genotype, counts_NLR)
design_NLR

#order levels
design_NLR$genotype <- ordered(design_NLR$genotype , levels=c("124_17","124_52","Barke"))

#plotting
#Note to remove duplicated outliers https://stackoverflow.com/questions/37498351/r-ggplot-geom-jitter-duplicates-outlier
p <- ggplot(design_NLR, aes(x=genotype, y=CPM, colour=genotype)) + ylim (0,1000)
p + geom_boxplot(outlier.shape = NA) + theme_bw() + geom_jitter(size=6,shape=21, position=position_jitter(0.3))+ scale_color_manual(values = c("#56B4E9","#E69F00","#0072B2")) + labs(x="Genotype",y="Normalised counts (CPM)", title = gene_name)
#save as a .eps for figure integration

#end